### ISSUE TITLE
Compiler flag to include all symbols defined in imported namespaces

### ISSUE THREAD

**Issue by Muzietto** [mattbierner/khepri#127]
Currently the compiler will import into a JS file only the symbols needed by the functions in the file itself. As example of including only few from a very large namespace:

https://github.com/Muzietto/khepri-lambda/blob/master/lambda/js-build/es_ch4.js

It would be useful to have a compiler flag that imports all symbols defined in the imported namespace.

The main reason is to allow easy debugging/exploring in the browser console after placing a breakpoint near a troublesome point of the execution.

**Comment by mattbierner** [comment]
I think this is worth doing.

Khepri performs a ratability pass during compilation which is what is removing your bindings:
https://github.com/mattbierner/khepri-compile/blob/master/lib/reachable/reachable.kep

This is important because the inlining stage generates a lot of nonsense bindings that would degrade performance and increase output code size. For experimentation, you can actually edit this file locally (https://github.com/mattbierner/khepri-compile/blob/master/lib/compile.kep) to remove any stages of compilation, including the readability one.

Most of the infrastructure in place to support this already. Here's how it would work:
* Attach user data to all important nodes during the lexical compiler stage to mark them as 'unprunable'.
* Because this happens before the inlining stage, any variable declarations/bindings generated by inlining could still be pruned.
* The actual reachability stage would check the unprunable property before deleting a node.

This should really be the default behavior with a flag to enable more aggressive pruning.

**Comment by Muzietto** [comment]
The day I'll be able to understand how your compiler works, I am going to pop some champagne :-)
In the meantime, thank you for taking this request into account. It will help me a lot to understand my own programs.
Have a good day,Marco

**Comment by mattbierner** [comment]
Fixed in V1.3:

The default behavior is to not prune unreachable user defined bindings. You can enable the old behavior with the `--prune` command line flag or passing `prune`: false to the compiler in its options.
