### ISSUE TITLE
How to get the n-th element of an array?

### ISSUE THREAD

**Issue by marco-faustinelli** [mattbierner/khepri#128]
This function is supposed to return the n-th element of an *args* array:

    \n -> args[n];

But its gets compiled into:

    (function(n) { return args([index[n]); })

Is it the way things are supposed to be?

If yes, what is the correct khepri syntax to get an element from an array?

BTW: also `\n -> { return args[n]; }` gets compiled the same way.

**Comment by mattbierner** [comment]
Because of application, `a[x]` is always evaluated as call `a` with the array of `[x]`.

You want `a.(x)` instead: https://github.com/mattbierner/khepri/wiki/Symbols-and-Operators#object-operators

You can also create a function that does this by writing `(.(n))` which translates into `\x -> x.(n);`, although I need to refine a few points of how the compiler handles this with mutable bindings.

**Comment by marco-faustinelli** [comment]
Got it. My sole observation is that calling it "object operators" makes it unlikely to be found by anyone looking for "array operators". Thank you for the fast reply. Cheers.
