### ISSUE TITLE
How to curry a function with n arguments?

### ISSUE THREAD

**Issue by marco-faustinelli** [mattbierner/khepri#130]
The following code takes a n-ary function and returns its curried version:

    curried := \fun -> \value -> ? (fun.length <= 1) : (fun value) : curried(fun @ value);

Is there a better idiomatic way to express this in khepri?

I can imagine a solution with `\...args -> args forEach { . . . . }` using the forEach of the 'tiny annotated stream library' in the examples, but it looks too complicated to me; at least complicated as my own solution.

I noticed the closed issue 123, which refers to a "Multi Partially Applied pattern". But I cannot find it in the docs. Is it possibly relevant to the solution of this case? 

Thank you for your attention.

**Comment by mattbierner** [comment]
As you note, the `@` operation by default only applies to two arguments. You can see this when it is converted to a function.

```
(@);

var __curry = (function(x, y) {
    return x.bind(null, y);
});
__curry;
```

As a language extension, mostly to make switching between a partially application and application easy, Khepri also supports the syntax `f@(arg1, arg2, ...)` which is the same as `f @ arg1 @ arg2 ...`. This also does not seem to fit your need for a higher order function. Issue 123 was about making other operators support this same syntax, such as `1 + (2, 3, 4)` but I found it made the language more inconsistent.

I wouldn't recommend basing anything off the length of a function in Javascript and I'm not sure I understand your example since it looks like it ends up calling `fun` with the same argument, but here are two thoughts:

```
var args := \...args -> args;

// Curry first set of arguments function is called with.
var curry := \f -> Function.prototype.call.bind(Function.prototype.bind, f, null);

var z := curry args;
z(1,2)(3,4) === [1,2, 3, 4];

// Curry an array of arguments the function is called with
var curry := \f -> Function.prototype.apply.bind(Function.prototype.call.bind(Function.prototype.bind, f, null), null);
var := curry args;
z([1,2])(3, 4) === [1, 2, 3, 4]
```

Let me know if that is what you are after.
